version: '2'
services:
    ticketsharing-app:
        image: ticketsharing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ticketsharing-postgresql:5432/ticketsharing
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ticketsharing-postgresql:
        extends:
            file: postgresql.yml
            service: ticketsharing-postgresql
